try{
    throw "Test Failed";
} catch(error){
    console.log(error);
}